### ISSUE TITLE
Deploy is breaking at render.com

### ISSUE THREAD

**Issue by kauefraga** [kauefraga/fastify-ts-api#1]
[b5a7f4e](https://github.com/kauefraga/fastify-ts-api/commit/b5a7f4edcd0054387b713933b3ea5bad7566ec0c)

build log:
```
May 11 09:18:54 PM  Done in 7.8s
May 11 09:18:54 PM  Error: Cannot find module 'node:process'
May 11 09:18:54 PM  Require stack:
May 11 09:18:54 PM  - /opt/render/project/src/node_modules/.pnpm/rollup@3.21.6/node_modules/rollup/dist/shared/rollup.js
May 11 09:18:54 PM  - /opt/render/project/src/node_modules/.pnpm/rollup@3.21.6/node_modules/rollup/dist/rollup.js
May 11 09:18:54 PM  - /opt/render/project/src/node_modules/.pnpm/tsup@6.7.0_typescript@5.0.4/node_modules/tsup/dist/index.js
May 11 09:18:54 PM  - /opt/render/project/src/node_modules/.pnpm/tsup@6.7.0_typescript@5.0.4/node_modules/tsup/dist/chunk-63C427GY.js
May 11 09:18:54 PM  - /opt/render/project/src/node_modules/.pnpm/tsup@6.7.0_typescript@5.0.4/node_modules/tsup/dist/cli-default.js
May 11 09:18:54 PM      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
May 11 09:18:54 PM      at Function.Module._load (internal/modules/cjs/loader.js:730:27)
May 11 09:18:54 PM      at Module.require (internal/modules/cjs/loader.js:957:19)
May 11 09:18:54 PM      at require (internal/modules/cjs/helpers.js:88:18)
May 11 09:18:54 PM      at Object.<anonymous> (/opt/render/project/src/node_modules/.pnpm/rollup@3.21.6/node_modules/rollup/dist/shared/rollup.js:12:19)
May 11 09:18:54 PM      at Module._compile (internal/modules/cjs/loader.js:1068:30)
May 11 09:18:54 PM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
May 11 09:18:54 PM      at Module.load (internal/modules/cjs/loader.js:933:32)
May 11 09:18:54 PM      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
May 11 09:18:54 PM      at Module.require (internal/modules/cjs/loader.js:957:19)
May 11 09:18:54 PM   ELIFECYCLE  Command failed with exit code 1.
May 11 09:18:54 PM  ==> Build failed 😞
```

**Comment by kauefraga** [comment]
It's not currently possible to deploy fastify at render.co.lm
